spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deliciousdb
    username: postgres
    password: utsha
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # ddl-auto: update
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 9080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

cors:
  allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:3002
