-- This is a placeholder for your baseline database migration script.
-- Since the schema was previously generated by Hibernate, you need to dump the existing schema
-- and place the DDL commands here. 
-- For PostgreSQL, you can generate this by running:
-- pg_dump -s -U postgres deliciousdb > V1__init.sql

-- Example:
-- CREATE TABLE users (...);
